sudo: true

language: cpp

compiler: g++

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test

    packages:
      - libboost1.55-all-dev
      - gcc-4.8
      - g++-4.8
cache:
  apt: true

before_script:
  - export CXX="g++-4.8"

script:
  - mkdir build && cd build
  - cmake ..
  - make